/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedErrorsNotFoundRouteImport } from './routes/_authenticated.errors.not-found'
import { Route as AuthenticatedErrorsForbiddenRouteImport } from './routes/_authenticated.errors.forbidden'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedErrorsNotFoundRoute =
  AuthenticatedErrorsNotFoundRouteImport.update({
    id: '/errors/not-found',
    path: '/errors/not-found',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedErrorsForbiddenRoute =
  AuthenticatedErrorsForbiddenRouteImport.update({
    id: '/errors/forbidden',
    path: '/errors/forbidden',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/errors/forbidden': typeof AuthenticatedErrorsForbiddenRoute
  '/errors/not-found': typeof AuthenticatedErrorsNotFoundRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/errors/forbidden': typeof AuthenticatedErrorsForbiddenRoute
  '/errors/not-found': typeof AuthenticatedErrorsNotFoundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/forbidden': typeof AuthenticatedErrorsForbiddenRoute
  '/_authenticated/errors/not-found': typeof AuthenticatedErrorsNotFoundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/errors/forbidden' | '/errors/not-found'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/errors/forbidden' | '/errors/not-found'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/errors/forbidden'
    | '/_authenticated/errors/not-found'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/errors/not-found': {
      id: '/_authenticated/errors/not-found'
      path: '/errors/not-found'
      fullPath: '/errors/not-found'
      preLoaderRoute: typeof AuthenticatedErrorsNotFoundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/errors/forbidden': {
      id: '/_authenticated/errors/forbidden'
      path: '/errors/forbidden'
      fullPath: '/errors/forbidden'
      preLoaderRoute: typeof AuthenticatedErrorsForbiddenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsForbiddenRoute: typeof AuthenticatedErrorsForbiddenRoute
  AuthenticatedErrorsNotFoundRoute: typeof AuthenticatedErrorsNotFoundRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsForbiddenRoute: AuthenticatedErrorsForbiddenRoute,
  AuthenticatedErrorsNotFoundRoute: AuthenticatedErrorsNotFoundRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
